title: My Courses Site
description: >
  A simple course directory site built with Jekyll.
theme: minima # or remove and use your own custom CSS
# Collections
collections:
  courses:
    output: true
    permalink: /courses/:path/

# Exclude stuff we don't want processed
exclude:
  - Gemfile
  - Gemfile.lock
